sudo: false

dist: trusty

language: go

go:
  - 1.5.3
  - 1.6
  - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1

matrix:
  allow_failures:
    - go: tip

before_install:
  - pip install --user codecov

install:
    - go get -u github.com/golang/lint/golint
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/sqs/goreturns
    - go get -u github.com/kisielk/errcheck
    - go get -u github.com/go-kit/kit/transport/http

branches:
  only:
    - "master"

script:
  - gofmt -l . | (! grep .) || (echo "Code differs from gofmt's style" && false)
  - goimports -l . | (! grep .) || (echo "goimports detect some issues" && false)
  - goreturns -l . | (! grep .) || (echo "goreturns detect some issues" && false)
  - errcheck ./...
  - go tool vet .
  - golint ./... | (! grep .) || (echo "Golint report some issues" && false)
  - find . -name *_test.go -exec go test -coverprofile={}.coverage.out -coverpkg="./..." {} \;
  - echo "mode\: set" > coverage.txt
  - find . -name *coverage.out -exec cat {} \; | grep "mode:" -v | sort | uniq >> coverage.txt

after_success:
  - codecov